app/Http/routes.php
<?php

/*
 * Neuronal View
 */
Route::get('/', 'NeuronalViewController@index')->name('neuronal-view');
Route::get('select-language/{lang}', 'LanguageController@selectLanguage')->name('select-language');

/*
 * Get more nodes ?????
 */
// Route::post('get-new-nodes', 'NeuronalViewController@getNewNodes');
Route::post('neuronal-view-get-page', 'NeuronalViewController@getPage');
Route::post('get-number-of-filtered-nodes', 'NeuronalViewController@countFiltered');
/*
 * Get filtered nodes
 */ 
// Route::post('get-filtered-nodes', 'NeuronalViewController@getFilteredNodes');

/*
 * Get edges for a node
 */
Route::post('get-memory-edges', 'NeuronalViewController@getMemoryEdges');

/*
 * Helper. Get countries by a continent
 */
Route::post('get-countries-by-continent', 'NeuronalViewController@getCountriesByContinent');

/* 
 * Detail View 
 */
Route::get('memory-details/{slug_name}~{memory_id}', 'DetailViewController@index')->name('detail-view');
Route::post('like-memory', 'DetailViewController@like')->name('like-a-memory');
Route::post('create-comment', 'DetailViewController@comment')->name('comment-a-memory');

/**
GOOGLE MAP
***/

Route::get('map-view', 'MapController@index')->name('map-view');
Route::post('gmap-load-memories', 'MapController@loadMemories')->name('gmap-load-memories');
/**
CREATE A MEMORY
*/

Route::get('recreate-your-memory/{provider?}', 'CreateController@index')->name('create');

Route::get('login-with-facebook', 'CreateController@redirectToFacebook')->name('login-with-facebook');
Route::get('login-with-twitter', 'CreateController@redirectToTwitter')->name('login-with-twitter');
Route::post('upload-person-photo', 'CreateController@uploadPersonPhoto')->name('upload-person-photo');
Route::post('finish-step-one', 'CreateController@finishStepOne')->name('finish-step-one');

Route::post('upload-memory-photo', 'CreateController@uploadMemoryPhoto')->name('upload-memory-photo');
Route::post('finish-step-two', 'CreateController@finishStepTwo')->name('finish-step-two');
Route::post('save-memory', 'CreateController@saveMemory')->name('save-memory');

/**
ADMIN
**/
Route::group(['namespace' => 'Admin', 'prefix' => 'moderation'], function() {

	Route::get('login', 'LoginController@index')->name('admin-login');
	Route::post('login', 'LoginController@login')->name('login-attempt');
	Route::get('logout', 'LoginController@logout')->name('admin-logout');

	Route::get('dashboard', 'DashboardController@index')->name('admin-dashboard');

	Route::get('memories', 'MemoriesController@index')->name('admin-memories');
	Route::post('memories-data', 'MemoriesController@tableData')->name('admin-memories-data');

	Route::get('persons', 'PersonsController@index')->name('admin-persons');
	Route::post('persons-data', 'PersonsController@tableData')->name('admin-persons-data');
});

app/Models/Comments/Comment.php
<?php namespace App\Models\Comments;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{

	protected $table = 'comments';
    protected $guarded = ['id'];


    public function moderation()
    {
        return $this->hasOne(\App\Models\CommentsModerations\CommentModeration::class, 'comment_id');
    }

    public function person()
    {
        return $this->belongsTo(\App\Models\Persons\Person::class, 'user_id');
    }

    public function getToCreatedAtAttribute()
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->created_at)->format('g:i A, j F Y');
    }
    
}

app/Http/Controllers/DetailViewController.php
<?php namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Edges\Edge;
use App\Models\Memories\VApprovedMemory as Memory;

class DetailViewController extends Controller
{

	/**
	 * Detail View
	 **/
	public function index($slug_name, $memory_id)
	{
		ini_set('max_execution_time', 0);

		/**
		 * Locate the memory record
		 */
		$memory = Memory::where('slug_name', $slug_name)->where('id', $memory_id)->first();
		if( ! $memory )
		{
			return redirect( route('neuronal-view') );
		}
		
		/*
		 * Paginate the memory comments 
		 */
		$comments = $memory->comments()->orderBy('created_at')->whereHas('moderation', function($q){
			$q->where('approved', 1);
		})->paginate(3);

		/*
		 * Actualizez numarul de comentarii
		 */
		$_memory = \App\Models\Memories\Memory::find($memory_id);
		$_memory->count_comments = $comments->total();
		$_memory->save();
		

		/**
		 * update number of views
		 **/
		$memory->getView(request()->ip());

		/**
		 * Am nevoie de 4 noduri conectate la nodul curent
		 * Ma uit in Edges (asta trebuie sa fie creata)
		 */
		$connected = Edge::whereRaw('(source_id=' . $memory->id . ') OR (target_id=' . $memory->id . ')')->orderBy('updated_at', 'desc')->paginate(4);	

		if($connected->count() < 4)
		{
			$populars = Memory::where('id', '<>', $memory->id)->orderBy('real_relevance', 'desc')->take(4 - $connected->count())->get();
		}
		else
		{
			$populars = null;
		}

		/**
		 * photos
		 **/
		$background = $memory->createPhoto(1280, 800, 'M', true, true);
		$memory_photo = $memory->createPhoto(480, 480, 'M');
		$user_photo = $memory->person->createPhoto(60, 60, 'P');
		/**
		 * Next comments page
		 **/
		if(request()->ajax())
		{
			return response()->json([
				'page-large' => view('detail-view._comments-page-large')->with([
					'comments' => $comments, 'k' => $comments->count()
				])->render(),
				'page-small' => view('detail-view._comments-page-small')->with([
					'comments' => $comments, 'k' => $comments->count()
				])->render(),
				'next-page-url' => str_replace( \URL::to('/') . '/', '', $comments->nextPageUrl()),
			]);
		}

		return 
			view('detail-view.index')
			->withPhotos([
				'background' => $background,
				'photo480'  => $memory_photo,
				'user60' => $user_photo,		
			])
			->withMemory($memory)
			->withComments($comments)
			->withConnected($connected)
			->withPopulars($populars)
			->withIsLiked($memory->isLiked(request()->ip()))
			->withNextCommentsUrl( str_replace( \URL::to('/') . '/', '', $comments->nextPageUrl()) )
		;
	}

	public function like(Request $request)
	{
		$memory = \App\Models\Memories\Memory::find($request->get('memory_id'));
		if(! $memory)
		{
			return response()->json(['success' => false]);
		}
		return response()->json($memory->getLike($request->ip()));
	}

	public function comment(Request $request)
	{
		$memory = \App\Models\Memories\Memory::find($request->get('memory_id'));
		if(! $memory)
		{
			return response()->json(['success' => false]);
		}
		return response()->json($memory->getComment($request->except(['_token', 'memory_id']) /* + ['client_ip' => $request->ip()] */));
	}

}

resources/views/detail-view/_comments-page-large.blade.php
<div class="comments-page" data-page="{{$comments->currentPage()}}">
	@foreach($comments as $i => $comment)
		<div class="comment-item-container {{ $i == $k-1 ? 'last-comment' : ''}}">
			<div class="comment-item-left">
				<div class="l-c-user">
					<div class="l-c-nickname">{{ $comment->nickname }}</div>
					<div class="l-c-created-at">{{ $comment->to_created_at }}</div>
				</div>
				<div class="clearfix"></div>
			</div>

			<div class="comment-item-right">
				{{ $comment->comment }}
			</div>

			<div class="clearfix"></div>
		</div>
	@endforeach
</div>

resources/views/detail-view/_comments-page-small.blade.php
<div class="comments-page" data-page="{{$comments->currentPage()}}">
	@foreach($comments as $i => $comment)
		<div class="comment-item-container {{ $i == $k-1 ? 'last-comment' : ''}}">
			
			<div class="user-infos-comment-row">

				<div class="user-comment-nickname">
					{{ $comment->nickname }}
				</div>

				<div class="comment-created-at">
					{{ $comment->to_created_at }}
				</div>

				<div class="clearfix"></div>
			</div>

			<div class="comment-body">
				{{ $comment->comment }}						
			</div>
		</div>
	@endforeach
</div>

resources/views/detail-view/_connection-photo.blade.php
{!! Html::image($memory->createPhoto(320, 320, 'M'), $memory->slug_name, ['class' => 'img-responsive img-connection']) !!}

<div class="connection-infos">
	<a href="{{ route('detail-view', ['memory_id' => $memory->id, 'slug_name' => $memory->slug_name]) }}" class="name">{{$memory->name}}</a>
	<div>
		<span class="location">{!! $memory->location !!}</span>
		<span class="date-of">{!! $memory->date_of !!}</span>
	</div>
	<div>
		<span class="likes">{!!$memory->number_of_likes!!}</span>
		<span class="comments">{!!$memory->number_of_comments!!}</span>
	</div>
</div>

<div class="connection-circles">
	@if($edge)
		@if($edge->year)
			<div>
				{!! Html::image('assets/small/yellow.png', 'yellow') !!}
			</div>
		@endif
		@if($edge->country_id)
			<div>
				{!! Html::image('assets/small/blue.png', 'blue') !!}
			</div>
		@endif
		@if($edge->tags)
			<div>
				{!! Html::image('assets/small/white.png', 'white') !!}
			</div>
		@endif
	@endif
</div>

resources/views/detail-view/index.blade.php
@extends('~layouts.master')

@section('styles')
	{!! Html::style('vendors/formvalidation/dist/css/formValidation.min.css') !!}
	{!! Html::style('css/detail-view.css') !!}
@stop

@section('scripts')
	<script>
		window.photos = {!! json_encode($photos) !!};
		window.memory = {!! $memory !!};
		window.validations = {!! json_encode(trans('detail-view.validations')) !!};
	</script>

	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2X74xWumQ1zt5WgBagWAszEpYJqC1nEU"></script>
	{!! Html::script('js/google-map/markerclusterer.js') !!}
	{!! Html::script('vendors/comptech/Collection.js') !!}
	{!! Html::script('js/google-map/mapview.js') !!}
	{!! Html::script('js/google-map/map-options.js') !!}
	{!! Html::script('js/google-map/jquery.mapview.js') !!}
	{!! Html::script('js/detail-view/share.js') !!}
	{!! Html::script('vendors/formvalidation/dist/js/formValidation.min.js') !!}
	{!! Html::script('vendors/formvalidation/dist/js/framework/bootstrap.min.js') !!}
	{!! Html::script('vendors/scroll-to/jquery-scrollto.js') !!}
	{!! Html::script('js/detail-view/rym-detail-view.js') !!}
	{!! Html::script('js/detail-view/run.js') !!}
@stop

@section('content')
	
	<input id="memory-id" type="hidden" value="{{$memory->id}}" />
	
	<div class="section-container for-small">
		@foreach([1, 2, 3, 4, 5, 6, 7, 8] as $i => $section)
			<div class="detail-section detail-section-{{$section}}">
				@include('detail-view._sections-small.' . $section)
			</div>
		@endforeach
	</div>

	<div class="section-container for-large">
		@foreach([1, 2, 4, 6, 7, 8] as $i => $section)
			<div class="detail-section detail-section-{{$section}}">
				@include('detail-view._sections-large.' . $section)
			</div>
		@endforeach
	</div>
	@include('detail-view._sections-large._actions')
@stop